import React, { useEffect, useRef } from 'react';

interface PrivacyPolicyProps {
  onClose: () => void;
}

const PrivacyPolicy: React.FC<PrivacyPolicyProps> = ({ onClose }) => {
  const modalRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    // Focus management for accessibility
    if (modalRef.current) {
      modalRef.current.focus();
    }

    // Trap focus inside the modal and allow closing with Escape key
    const handleKeyDown = (event: KeyboardEvent) => {
      if (event.key === 'Escape') {
        onClose();
      }
      // Add more sophisticated focus trapping if needed, for now a simple trap is omitted for brevity.
    };

    document.addEventListener('keydown', handleKeyDown);
    return () => {
      document.removeEventListener('keydown', handleKeyDown);
    };
  }, [onClose]);

  return (
    <div
      ref={modalRef}
      className="relative bg-white shadow-xl rounded-lg p-6 md:p-10 w-full max-w-4xl max-h-[90vh] overflow-y-auto focus:outline-none"
      tabIndex={-1} // Make div focusable
      aria-labelledby="privacy-policy-title"
    >
      <button
        onClick={onClose}
        className="absolute top-4 right-4 text-gray-600 hover:text-gray-900 text-2xl font-bold"
        aria-label="Close privacy policy"
      >
        &times;
      </button>

      <h1 id="privacy-policy-title" className="text-3xl font-bold mb-6 text-center text-blue-700">Privacy Policy for Gemini Reels & Stories Bot</h1>
      <p className="mb-4 text-sm text-gray-600 text-center">Last updated: May 15, 2024</p>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-3 text-blue-600">Introduction</h2>
        <p className="mb-3">
          Welcome to the Gemini Reels & Stories Bot (the "Bot"). This Privacy Policy explains how we collect, use, store, and disclose information from users interacting with our Bot, both through its web interface and the integrated Facebook Messenger service.
          By using our Bot, you agree to the collection and use of information in accordance with this policy.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-3 text-blue-600">1. Information We Collect</h2>
        <p className="mb-3">
          We collect information necessary to provide and improve our services. The types of information collected depend on how you interact with the Bot:
        </p>
        <ul className="list-disc list-inside ml-4 mb-3">
          <li className="mb-1"><strong>Messenger User ID:</strong> When you interact with the Bot via Facebook Messenger, we collect your unique Messenger User ID to identify you and send messages back to you.</li>
          <li className="mb-1"><strong>Message Content:</strong> We collect the text of your messages, prompts, queries, and any attachments (e.g., images) you send to the Bot.</li>
          <li className="mb-1"><strong>Generated Content:</strong> Any text, image URLs, video URLs, or audio URLs generated by the Bot in response to your requests.</li>
          <li className="mb-1"><strong>Timestamps:</strong> The date and time of your interactions with the Bot.</li>
          <li className="mb-1"><strong>Full Messenger Event Payload:</strong> For diagnostic and operational purposes, we may store the complete event payload received from Facebook Messenger.</li>
          <li className="mb-1"><strong>Scheduled Post Data (Web App Only):</strong> If you use the "Schedule Post" feature in the web application, the details of your scheduled posts (e.g., content, scheduled time, original message ID) are stored locally in your browser's local storage. This data is not transmitted to our servers or Facebook.</li>
        </ul>
        <p className="mb-3">
          We do NOT collect personally identifiable information (PII) such as your name, email address, or other contact details beyond what is provided by the Messenger platform and necessary for communication.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-3 text-blue-600">2. How We Collect Information</h2>
        <p className="mb-3">
          Information is collected through the following methods:
        </p>
        <ul className="list-disc list-inside ml-4 mb-3">
          <li className="mb-1"><strong>Facebook Messenger Webhook:</strong> When you send a message to our Bot on Facebook Messenger, the Messenger Platform sends your message and associated metadata to our Netlify Function via a webhook.</li>
          <li className="mb-1"><strong>Web Application Interface:</strong> When you interact with the Bot directly through its web application, your input is sent to our backend for processing. Local scheduling data is stored directly in your browser.</li>
        </ul>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-3 text-blue-600">3. How We Use Your Information</h2>
        <p className="mb-3">
          Your information is used for the following purposes:
        </p>
        <ul className="list-disc list-inside ml-4 mb-3">
          <li className="mb-1"><strong>To Operate the Bot:</strong> To process your requests, generate responses using the Gemini API, and send replies back to you.</li>
          <li className="mb-1"><strong>Content Generation:</strong> To generate creative text, edit images, or synthesize speech based on your prompts.</li>
          <li className="mb-1"><strong>Scheduling (Web App Only):</strong> To store and manage your locally scheduled posts within the web application.</li>
          <li className="mb-1"><strong>Improvement and Debugging:</strong> To understand how the Bot is used, diagnose issues, and improve the quality and relevance of its responses.</li>
        </ul>
        <p className="mb-3">
          We do NOT use your information for advertising, marketing, or to build profiles for purposes unrelated to the Bot's core functionality.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-3 text-blue-600">4. Information Sharing and Disclosure</h2>
        <p className="mb-3">
          We do not sell, trade, or otherwise transfer your personal information to outside parties. However, we do rely on the following third-party services for the Bot's operation:
        </p>
        <ul className="list-disc list-inside ml-4 mb-3">
          <li className="mb-1"><strong>Facebook Messenger Platform:</strong> For handling messaging communication with you. Your interactions are subject to Facebook's own privacy policies.</li>
          <li className="mb-1"><strong>Google Gemini API:</strong> For processing your prompts and generating AI-powered responses (text, image edits, speech). Your prompts are sent to the Gemini API. Please refer to Google's privacy policy for more information on how they handle data.</li>
          <li className="mb-1"><strong>MongoDB Atlas:</strong> For securely storing user interactions and generated content in a database. MongoDB Atlas's privacy policy applies to their data handling practices.</li>
          <li className="mb-1"><strong>Netlify:</strong> For hosting the web application and the serverless functions that power the Messenger webhook. Netlify's privacy policy applies to their hosting services.</li>
        </ul>
        <p className="mb-3">
          We may also disclose your information if required to do so by law or in response to valid requests by public authorities (e.g., a court order or government agency).
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-3 text-blue-600">5. Data Storage and Security</h2>
        <p className="mb-3">
          Your Messenger User ID, message content, and generated content are stored in a MongoDB database. We implement reasonable security measures designed to protect your information from unauthorized access, alteration, disclosure, or destruction. However, no internet transmission or electronic storage is 100% secure, and we cannot guarantee absolute security.
        </p>
        <p className="mb-3">
          Please note that scheduling data used by the web application's "Schedule Post" feature is stored <em>only</em> in your browser's local storage and is not transferred to our servers. Clearing your browser data will delete this information.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-3 text-blue-600">6. Data Retention</h2>
        <p className="mb-3">
          We retain the information collected for as long as necessary to fulfill the purposes outlined in this Privacy Policy, or as required by law.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-3 text-blue-600">7. Your Rights - Data Deletion</h2>
        <p className="mb-3">
          You have the right to request the deletion of your data. The process for data deletion depends on how you interacted with the bot:
        </p>
        <ul className="list-disc list-inside ml-4 mb-3">
          <li className="mb-1">
            <strong>For Facebook Messenger Data:</strong> If you have interacted with our Bot via Facebook Messenger, you can initiate a data deletion request directly through Facebook. Navigate to your Facebook settings, find "Apps and Websites," locate "Gemini Reels & Stories Bot," and request data deletion. Facebook will then send a callback to our server, and all your associated data (e.g., Messenger User ID, message content) stored in our MongoDB database will be permanently deleted.
          </li>
          <li className="mb-1">
            <strong>For Web Application Local Data (Scheduled Posts):</strong> The "Schedule Post" feature in the web application stores data locally in your browser's storage. To delete this data, simply navigate to the "Data Mgmt" feature within the bot's web interface and click the "Clear Local Scheduled Posts" button. This will instantly remove all scheduled post data from your browser.
          </li>
          <li className="mb-1">
            For any other data-related inquiries or to exercise other rights (e.g., access, correction), please contact the Facebook Page associated with this Bot directly via Messenger.
          </li>
        </ul>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-3 text-blue-600">8. Changes to This Privacy Policy</h2>
        <p className="mb-3">
          We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the "Last updated" date. You are advised to review this Privacy Policy periodically for any changes.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-3 text-blue-600">9. Contact Us</h2>
        <p className="mb-3">
          If you have any questions about this Privacy Policy, please contact us through the Facebook Page associated with the Bot.
        </p>
      </section>
      <p className="text-center text-gray-500 text-sm mt-8">
        This bot is for demonstration purposes only and does not constitute a commercial service.
      </p>
    </div>
  );
};

export default PrivacyPolicy;