import React, { useEffect, useRef } from 'react';

interface TermsOfServiceProps {
  onClose: () => void;
}

const TermsOfService: React.FC<TermsOfServiceProps> = ({ onClose }) => {
  const modalRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    // Focus management for accessibility
    if (modalRef.current) {
      modalRef.current.focus();
    }

    // Trap focus inside the modal and allow closing with Escape key
    const handleKeyDown = (event: KeyboardEvent) => {
      if (event.key === 'Escape') {
        onClose();
      }
      // Add more sophisticated focus trapping if needed, for now a simple trap is omitted for brevity.
    };

    document.addEventListener('keydown', handleKeyDown);
    return () => {
      document.removeEventListener('keydown', handleKeyDown);
    };
  }, [onClose]);

  return (
    <div
      ref={modalRef}
      className="relative bg-white shadow-xl rounded-lg p-6 md:p-10 w-full max-w-4xl max-h-[90vh] overflow-y-auto focus:outline-none"
      tabIndex={-1} // Make div focusable
      aria-labelledby="terms-of-service-title"
    >
      <button
        onClick={onClose}
        className="absolute top-4 right-4 text-gray-600 hover:text-gray-900 text-2xl font-bold"
        aria-label="Close terms of service"
      >
        &times;
      </button>

      <h1 id="terms-of-service-title" className="text-3xl font-bold mb-6 text-center text-blue-700">Terms of Service - Gemini Reels & Stories Bot</h1>
      <p className="mb-4 text-sm text-gray-600 text-center">Last updated: May 15, 2024</p>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-3 text-blue-600">1. Acceptance of Terms</h2>
        <p className="mb-3">
          By accessing or using the Gemini Reels & Stories Bot (the "Bot"), you agree to be bound by these Terms of Service ("Terms") and our Privacy Policy. If you do not agree to these Terms, do not use the Bot. This Bot is provided for demonstration and experimental purposes only and is not intended for commercial use.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-3 text-blue-600">2. Description of Service</h2>
        <p className="mb-3">
          The Bot is an AI-powered social media assistant that simulates the creation of content for platforms like Facebook and Instagram. Features include text generation, image editing, story creation with optional voice narration and song suggestions, and local post scheduling. All "posting" and "scheduling" are simulated within the application and do not interact directly with live social media platforms.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-3 text-blue-600">3. User Conduct</h2>
        <p className="mb-3">
          You agree to use the Bot responsibly and lawfully. You shall not use the Bot to:
        </p>
        <ul className="list-disc list-inside ml-4 mb-3">
          <li className="mb-1">Generate or promote illegal, harmful, threatening, abusive, harassing, defamatory, vulgar, obscene, or otherwise objectionable content.</li>
          <li className="mb-1">Infringe upon the rights of others, including copyright, trademark, privacy, or publicity rights.</li>
          <li className="mb-1">Transmit any content that contains viruses, malware, or other harmful code.</li>
          <li className="mb-1">Impersonate any person or entity, or falsely state or otherwise misrepresent your affiliation with a person or entity.</li>
        </ul>
        <p className="mb-3">
          We reserve the right to suspend or terminate your access to the Bot for any violation of these Terms.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-3 text-blue-600">4. Intellectual Property</h2>
        <p className="mb-3">
          The content generated by the Bot is produced by an artificial intelligence model. While you are free to use content you generate for personal, non-commercial purposes, you acknowledge that the Bot itself and its underlying technologies are owned by the developers and Google. We make no warranty regarding the originality or intellectual property status of generated content.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-3 text-blue-600">5. Disclaimers and Limitation of Liability</h2>
        <p className="mb-3">
          THE BOT IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT ANY WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. WE DO NOT WARRANT THAT THE BOT WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE OF HARMFUL COMPONENTS.
        </p>
        <p className="mb-3">
          IN NO EVENT SHALL THE DEVELOPERS OF THIS BOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES, WHETHER INCURRED DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, RESULTING FROM (A) YOUR ACCESS TO OR USE OF OR INABILITY TO ACCESS OR USE THE BOT; (B) ANY CONDUCT OR CONTENT OF ANY THIRD PARTY ON THE BOT; OR (C) UNAUTHORIZED ACCESS, USE, OR ALTERATION OF YOUR TRANSMISSIONS OR CONTENT.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-3 text-blue-600">6. Changes to Terms</h2>
        <p className="mb-3">
          We reserve the right to modify these Terms at any time. We will notify you of any changes by posting the new Terms on this page. Your continued use of the Bot after any such changes constitutes your acceptance of the new Terms.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-3 text-blue-600">7. Governing Law</h2>
        <p className="mb-3">
          These Terms shall be governed by and construed in accordance with the laws of the jurisdiction where the Bot is operated, without regard to its conflict of law principles.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-3 text-blue-600">8. Contact Information</h2>
        <p className="mb-3">
          If you have any questions about these Terms of Service, please contact us through the Facebook Page associated with the Bot.
        </p>
      </section>

      <p className="text-center text-gray-500 text-sm mt-8">
        This bot is for demonstration purposes only and does not constitute a commercial service.
      </p>
    </div>
  );
};

export default TermsOfService;